"""empty message

Revision ID: 091f0d9621c0
Revises: 8568afb1964f
Create Date: 2024-01-17 12:02:17.600372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '091f0d9621c0'
down_revision: Union[str, None] = '8568afb1964f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('user_order_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'user_order_num')
    # ### end Alembic commands ###
