"""empty message

Revision ID: 0cdb3cf22961
Revises: 59c8506b8f72
Create Date: 2023-12-27 03:56:00.911102

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0cdb3cf22961'
down_revision: Union[str, None] = '59c8506b8f72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boxtypes', sa.Column('box_name', sa.String(), nullable=False))
    op.add_column('boxtypes', sa.Column('pricing_default', sa.Float(), nullable=True))
    op.add_column('boxtypes', sa.Column('volume', sa.Float(), nullable=True))
    op.add_column('boxtypes', sa.Column('weight_limit', sa.Float(), nullable=True))
    op.add_column('order_statuses', sa.Column('status_name', sa.String(), nullable=False))
    op.add_column('order_statuses', sa.Column('description', sa.String(), nullable=False))
    op.add_column('orders', sa.Column('address_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('box_type_id', sa.UUID(), nullable=True))
    op.add_column('orders', sa.Column('box_count', sa.Integer(), nullable=True))
    op.add_column('orders', sa.Column('status', sa.UUID(), nullable=True))
    op.drop_constraint('orders_address_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'address', ['address_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'boxtypes', ['box_type_id'], ['id'])
    op.create_foreign_key(None, 'orders', 'order_statuses', ['status'], ['id'])
    op.drop_column('orders', 'disabled')
    op.drop_column('orders', 'payment_day')
    op.drop_column('orders', 'tariff')
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'subscription')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('subscription', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('address', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('tariff', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('payment_day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('disabled', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_address_fkey', 'orders', 'address', ['address'], ['id'])
    op.drop_column('orders', 'status')
    op.drop_column('orders', 'box_count')
    op.drop_column('orders', 'box_type_id')
    op.drop_column('orders', 'address_id')
    op.drop_column('order_statuses', 'description')
    op.drop_column('order_statuses', 'status_name')
    op.drop_column('boxtypes', 'weight_limit')
    op.drop_column('boxtypes', 'volume')
    op.drop_column('boxtypes', 'pricing_default')
    op.drop_column('boxtypes', 'box_name')
    # ### end Alembic commands ###
