"""empty message

Revision ID: 1fdf3c17377b
Revises: 92c92a1152c4
Create Date: 2024-02-08 02:52:24.531622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fdf3c17377b'
down_revision: Union[str, None] = '92c92a1152c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_types', sa.Column('type_name', sa.String(), nullable=False))
    op.add_column('regions', sa.Column('region_type', sa.String(), nullable=False))
    op.add_column('regions', sa.Column('geodata', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('regions', 'geodata')
    op.drop_column('regions', 'region_type')
    op.drop_column('notification_types', 'type_name')
    # ### end Alembic commands ###
