"""empty message

Revision ID: 3ddf7297e8a3
Revises: 4f0d3afa0275
Create Date: 2024-01-24 17:21:06.134020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ddf7297e8a3'
down_revision: Union[str, None] = '4f0d3afa0275'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('interval', sa.String(), nullable=True))
    op.drop_column('address', 'intreval')
    op.drop_column('address', 'day')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('address', sa.Column('intreval', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('address', 'interval')
    # ### end Alembic commands ###
