"""empty message

Revision ID: 43418bf9a479
Revises: 0cdb3cf22961
Create Date: 2023-12-27 17:26:59.798892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '43418bf9a479'
down_revision: Union[str, None] = '0cdb3cf22961'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('date_created', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('last_updated', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'last_updated')
    op.drop_column('orders', 'date_created')
    # ### end Alembic commands ###
