"""empty message

Revision ID: 4f0d3afa0275
Revises: 3b6c05914c51
Create Date: 2024-01-23 02:52:07.958570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4f0d3afa0275'
down_revision: Union[str, None] = '3b6c05914c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('day', sa.DateTime(), nullable=True))
    op.add_column('address', sa.Column('on_interval', sa.Boolean(), nullable=True))
    op.add_column('address', sa.Column('interval_type', sa.String(), nullable=True))
    op.add_column('address', sa.Column('intreval', sa.String(), nullable=True))
    op.add_column('address', sa.Column('last_disposal', sa.DateTime(), nullable=True))
    op.add_column('address', sa.Column('next_planned_date', sa.DateTime(), nullable=True))
    op.add_column('address', sa.Column('times_completed', sa.Integer(), nullable=True))
    op.drop_column('orders', 'interval_type')
    op.drop_column('orders', 'on_interval')
    op.drop_column('orders', 'times_completed')
    op.drop_column('orders', 'intreval')
    op.drop_column('orders', 'next_planned_date')
    op.drop_column('orders', 'day')
    op.drop_column('orders', 'last_disposal')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('last_disposal', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('day', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('next_planned_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('intreval', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('times_completed', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('on_interval', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('orders', sa.Column('interval_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('address', 'times_completed')
    op.drop_column('address', 'next_planned_date')
    op.drop_column('address', 'last_disposal')
    op.drop_column('address', 'intreval')
    op.drop_column('address', 'interval_type')
    op.drop_column('address', 'on_interval')
    op.drop_column('address', 'day')
    # ### end Alembic commands ###
