"""empty message

Revision ID: 59c8506b8f72
Revises: d5989fc98644
Create Date: 2023-12-25 18:06:49.200870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59c8506b8f72'
down_revision: Union[str, None] = 'd5989fc98644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('detail', sa.String(), nullable=True))
    op.add_column('address', sa.Column('comment', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('address', 'comment')
    op.drop_column('address', 'detail')
    # ### end Alembic commands ###
