"""empty message

Revision ID: 747f0ce9677d
Revises: cab5f962e7fb
Create Date: 2024-01-11 18:46:33.657239

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '747f0ce9677d'
down_revision: Union[str, None] = 'cab5f962e7fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('address', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('boxtypes', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('days_work', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notification_types', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.add_column('order_status_history', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('order_statuses', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('orders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('payments', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('routed_orders', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'routed_orders', 'orders', ['order_id'], ['id'])
    op.add_column('users', sa.Column('disabled', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users_address', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.alter_column('week_days_work', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('week_days_work', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('users_address', 'deleted_at')
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'disabled')
    op.drop_constraint(None, 'routed_orders', type_='foreignkey')
    op.drop_column('routed_orders', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('permissions', 'deleted_at')
    op.drop_column('payments', 'deleted_at')
    op.drop_column('orders', 'deleted_at')
    op.drop_column('order_statuses', 'deleted_at')
    op.drop_column('order_status_history', 'deleted_at')
    op.alter_column('notifications', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('notification_types', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('days_work', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('boxtypes', 'deleted_at')
    op.drop_column('address', 'deleted_at')
    # ### end Alembic commands ###
