"""empty message

Revision ID: 8dbded9fc6e5
Revises: 43418bf9a479
Create Date: 2023-12-27 19:42:14.002131

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dbded9fc6e5'
down_revision: Union[str, None] = '43418bf9a479'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('day', sa.String(), nullable=True))
    op.drop_column('orders', 'weekday')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('weekday', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('orders', 'day')
    # ### end Alembic commands ###
