"""empty message

Revision ID: c012e27f8af5
Revises: 3ddf7297e8a3
Create Date: 2024-01-24 17:45:53.850888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c012e27f8af5'
down_revision: Union[str, None] = '3ddf7297e8a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('day', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'day')
    # ### end Alembic commands ###
