"""empty message

Revision ID: d5989fc98644
Revises: de004fe172e0
Create Date: 2023-12-25 13:23:18.745229

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd5989fc98644'
down_revision: Union[str, None] = 'de004fe172e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('secondname', sa.String(), nullable=True))
    op.drop_column('users', 'user_secondname')
    op.drop_column('users', 'user_firstname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('user_secondname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'secondname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
