"""empty message

Revision ID: de004fe172e0
Revises: eaae38d0c642
Create Date: 2023-12-25 13:21:59.571805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de004fe172e0'
down_revision: Union[str, None] = 'eaae38d0c642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'permissions', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.add_column('users', sa.Column('user_firstname', sa.String(), nullable=True))
    op.add_column('users', sa.Column('user_secondname', sa.String(), nullable=True))
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_secondname')
    op.drop_column('users', 'user_firstname')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'permissions', type_='unique')
    # ### end Alembic commands ###
