BUTTONS = {
    'MENU': '📖 Главное меню',
    'START': '▶️ Запустить бота',
    'SETTINGS': '⚙️Настройки',
    'CREATE_ORDER': '📝 Создать заявку',
    'ORDER_HISTORY': '📚 История заявок',
    'MY_ADDRESSES': '📍Мои адреса',
    'ADD_ADDRESS': '➕ Добавить адрес',
    'PAYMENTS': '💰 Способы оплаты',
    'QUESTIONNAIRE': '👤 Анкета',
    'NOTIFICATIONS': '📌 Уведомления',
    'ABOUT': '❓Как работает сервис',
    'DEFAULT': '🖍 Выбрать основной адрес',
    'DELETE_ADDRESS': '❌ Удалить адрес',
    'PHONE_NUMBER': '📱️ Номер телефона',
    'EMAIL': '✉️️ Email',
    'SHARE_PHONE': '📱️ Поделиться номером',
    'START_BOT': '▶️ Начать пользовать ботом',
    'SHOW': '👀 Посмотреть',
    'PREVIOUS': '⬅️',
    'NEXT': '➡️',
    'SCHEDULE': '📆 Расписание вызова',
    'FIRST_NAME': '1️⃣ Имя',
    'LAST_NAME': '2️⃣ Фамилия',
    'BACK_TO_ORDER': '⬅️ Назад к просмотру заявки',
    'ROUTE': '🗺️ Маршрут',
    'BACK_ROUTE': '⬅️ Назад'
}
